mysql -u root -p$MYSQL_ROOT_PASSWORD --execute "CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}-test\`;CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}-test\`.* TO '$MYSQL_USER'@'%' WITH GRANT OPTION;FLUSH PRIVILEGES;"

echo "** Finished creating test DB and users"